import type { Metadata } from 'next';
import localFont from 'next/font/local';
import TransitionProvider from '@/user/provider/transition-provider';
import { Header } from '@/user/layout/header';
import './styles/globals.css';

const myFont = localFont({
  src: '../public/font/archia-regular-webfont.woff',
  display: 'swap',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className={`${myFont.className} bg-[#14142B] text-[#FAFBFC]`}>
        <TransitionProvider>
          <Header />
          {children}
        </TransitionProvider>
      </body>
    </html>
  );
}
